Added factories for Rental & Purchase
joshua-newhouse/movie-rental pull request #1
Opened 2019-11-23 21:57 UTC by svk2000

Added Rental & Purchase factories

2019-11-23 22:52 UTC, joshua-newhouse requested changes
The Factories look good but you checked in all of your Intellij files.  Can you put a gitignore for all of the .idea/* files and remove them from the PR?

2019-11-24 16:22 UTC, svk2000 commented
Added Only Factories and Test driver. Please review

2019-11-24 16:22 UTC, svk2000 commented
@joshua-newhouse

2019-11-25 01:36 UTC, joshua-newhouse approved these changes

2019-11-25 01:37 UTC, merged